configs:
  params:
    server.insecure: true

server:
  enabled: true
  insecure: true
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 80
        targetPort: 8080

controller:
  replicas: 1

repoServer:
  replicas: 1

installCRDs: true
applicationSet:
  replicas: 1
  enabled: true

dex:
  enabled: false

redis:
  enabled: true
