configs:
  params:
    server.insecure: true

server:
  service:
    type: ClusterIP
# Access ArgoCD via: kubectl port-forward -n argocd svc/argocd-server 8080:80

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

dex:
  enabled: false

redis:
  enabled: true