apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-east
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/earpjennings37/say_when.git
    path: apps/usge1/argocd
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true